#!/bin/sh

# Specify the directory for the hooks.
# We'll use the current one (.githooks)
hookdir=$(dirname $0)

# "$hookdir/areYouSure.sh"
exec < /dev/tty
read -p "Are you sure you want to commit this (y/n)? " answer
echo $answer
# Specify the hooks you want to run during the pre-commit process:
# "$hookdir/areYouSure.sh"
# && $hookdir/add-your-own-scripts-here"
