#!/bin/sh

# Specify the directory for the hooks.
# We'll use the current one (.githooks)
hookdir=$(dirname $0)

# Specify the hooks you want to run during the pre-commit process:
"$hookdir/beforePush.sh"
# && $hookdir/add-your-own-scripts-here"